import t1 from '../../assets/img/t1.jpeg'
import t2 from '../../assets/img/t2.jpeg'
import t3 from '../../assets/img/t3.jpeg'
import t4 from '../../assets/img/t4.jpeg'
import t5 from '../../assets/img/t5.jpeg'
import t6 from '../../assets/img/t6.jpeg'
import t7 from '../../assets/img/t7.jpeg'
import t8 from '../../assets/img/t8.jpeg'
import t9 from '../../assets/img/t9.jpeg'
import t10 from '../../assets/img/t10.jpeg'
import t11 from '../../assets/img/t11.jpeg'
import t12 from '../../assets/img/t12.jpeg'
import t13 from '../../assets/img/t13.jpeg'
import t14 from '../../assets/img/t14.jpeg'
import t15 from '../../assets/img/t15.jpeg'
const images=[t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15]
export default images;